//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevelopmentChallenge.Data.Idiomas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_it {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_it() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevelopmentChallenge.Data.Idiomas.Resource-it", typeof(Resource_it).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La zona .
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerchio.
        /// </summary>
        public static string Circulo {
            get {
                return ResourceManager.GetString("Circulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerchi.
        /// </summary>
        public static string Circulos {
            get {
                return ResourceManager.GetString("Circulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Piazza.
        /// </summary>
        public static string Cuadrado {
            get {
                return ResourceManager.GetString("Cuadrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Piazze.
        /// </summary>
        public static string Cuadrados {
            get {
                return ResourceManager.GetString("Cuadrados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;h1&gt;Rapporto forma&lt;/h1&gt;2 quadrati | Area 29 | Perimetro 28 &lt;br/&gt;2 cerchi | Area 13.01 | Perimetro 18.06 &lt;br/&gt;3 triangoli | Area 49.64 | Perimetro 51,6 &lt;br/&gt;TOTALE:&lt;br/&gt;7 forme Perimetro 97,66 Area 91,65:.
        /// </summary>
        public static string FormaReporte {
            get {
                return ResourceManager.GetString("FormaReporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a forme.
        /// </summary>
        public static string Formas {
            get {
                return ResourceManager.GetString("Formas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;h1&gt;Rapporto forma&lt;/h1&gt;1 quadrato | Area 25 | Perimetro 20 &lt;br/&gt;TOTALE:&lt;br/&gt;1 forme Perimetro 20 Area 25:.
        /// </summary>
        public static string InfoCuadrado {
            get {
                return ResourceManager.GetString("InfoCuadrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;h1&gt;Rapporto forme&lt;/h1&gt;3 quadrati | Area 35 | Perimetro 36 &lt;br/&gt;TOTALE:&lt;br/&gt;3 forme Perimetro 36 Area 35:.
        /// </summary>
        public static string InfoCuadrados {
            get {
                return ResourceManager.GetString("InfoCuadrados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;h1&gt;Elenco vuoto di forme!&lt;/h1&gt;.
        /// </summary>
        public static string ListaVacia {
            get {
                return ResourceManager.GetString("ListaVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perimetro.
        /// </summary>
        public static string Perimetro {
            get {
                return ResourceManager.GetString("Perimetro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si è verificato un errore durante l&apos;esecuzione del test.
        /// </summary>
        public static string PruebaError {
            get {
                return ResourceManager.GetString("PruebaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rettangolo.
        /// </summary>
        public static string Rectangulo {
            get {
                return ResourceManager.GetString("Rectangulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Il rettangolo non può avere tutti i lati uguali..
        /// </summary>
        public static string RectanguloIncorrecto {
            get {
                return ResourceManager.GetString("RectanguloIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rettangoli.
        /// </summary>
        public static string Rectangulos {
            get {
                return ResourceManager.GetString("Rectangulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;h1&gt;Rapporto moduli&lt;/h1&gt;.
        /// </summary>
        public static string Reporte {
            get {
                return ResourceManager.GetString("Reporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TOTALE:&lt;br/&gt;.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trapezio.
        /// </summary>
        public static string Trapecio {
            get {
                return ResourceManager.GetString("Trapecio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Le basi del trapezio isoscele non possono essere uguali.
        /// </summary>
        public static string TrapecioIsoscelesIncorrecto {
            get {
                return ResourceManager.GetString("TrapecioIsoscelesIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Le basi e/o i lati di un trapezio rettangolo non possono essere uguali..
        /// </summary>
        public static string TrapecioRectanguloIncorrecto {
            get {
                return ResourceManager.GetString("TrapecioRectanguloIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trapezio.
        /// </summary>
        public static string Trapecios {
            get {
                return ResourceManager.GetString("Trapecios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Triangulo.
        /// </summary>
        public static string Triangulo {
            get {
                return ResourceManager.GetString("Triangulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a triangoli.
        /// </summary>
        public static string Triangulos {
            get {
                return ResourceManager.GetString("Triangulos", resourceCulture);
            }
        }
    }
}
